name: "GivTCP-DEV (Texelo hotfix)"
description: "TCP Modbus connection to MQTT/JSON for Givenergy Battery/PV Invertors - 3.5.47 + HV stack API fix"
version: "3.5.47-hotfix19"
slug: "givtcp-dev-texelo-hotfix"
homeassistant_api: true
hassio_api: true
init: true
ingress: true
services:
  - "mqtt:want"
map:
  - config:rw
  - ssl
boot: auto
url: https://github.com/Texelo/giv_tcp/tree/hotfix/3.5.47-hvstack-api/addons/givtcp-dev-hotfix
legacy: true
arch:
  - aarch64
  - amd64
host_network: true
